"""Pydantic schemas for API request/response models."""

from fastsmtp.schemas.common import ErrorResponse, HealthResponse, MessageResponse, ReadyResponse
from fastsmtp.schemas.domain import (
    DomainBase,
    DomainBriefResponse,
    DomainCreate,
    DomainResponse,
    DomainUpdate,
    MemberBase,
    MemberCreate,
    MemberResponse,
    MemberUpdate,
)
from fastsmtp.schemas.recipient import (
    RecipientBase,
    RecipientCreate,
    RecipientResponse,
    RecipientUpdate,
)
from fastsmtp.schemas.rule import (
    RuleBase,
    RuleCreate,
    RuleReorderRequest,
    RuleResponse,
    RuleSetBase,
    RuleSetCreate,
    RuleSetResponse,
    RuleSetUpdate,
    RuleSetWithRulesResponse,
    RuleUpdate,
)
from fastsmtp.schemas.user import (
    APIKeyBase,
    APIKeyCreate,
    APIKeyCreateResponse,
    APIKeyResponse,
    UserBase,
    UserBriefResponse,
    UserCreate,
    UserResponse,
    UserUpdate,
    WhoamiResponse,
)
from fastsmtp.schemas.webhook import (
    DeliveryLogDetailResponse,
    DeliveryLogFilter,
    DeliveryLogResponse,
    TestWebhookRequest,
    TestWebhookResponse,
)

__all__ = [
    "APIKeyBase",
    "APIKeyCreate",
    "APIKeyCreateResponse",
    "APIKeyResponse",
    "DeliveryLogDetailResponse",
    "DeliveryLogFilter",
    "DeliveryLogResponse",
    "DomainBase",
    "DomainBriefResponse",
    "DomainCreate",
    "DomainResponse",
    "DomainUpdate",
    "ErrorResponse",
    "HealthResponse",
    "MemberBase",
    "MemberCreate",
    "MemberResponse",
    "MemberUpdate",
    "MessageResponse",
    "ReadyResponse",
    "RecipientBase",
    "RecipientCreate",
    "RecipientResponse",
    "RecipientUpdate",
    "RuleBase",
    "RuleCreate",
    "RuleReorderRequest",
    "RuleResponse",
    "RuleSetBase",
    "RuleSetCreate",
    "RuleSetResponse",
    "RuleSetUpdate",
    "RuleSetWithRulesResponse",
    "RuleUpdate",
    "TestWebhookRequest",
    "TestWebhookResponse",
    "UserBase",
    "UserBriefResponse",
    "UserCreate",
    "UserResponse",
    "UserUpdate",
    "WhoamiResponse",
]
